- frontend/.dockerignore
- frontend/Dockerfile
- frontend/nginx.conf
Dockerfile and nginx 
**Changes**
- Modifying dockerfile
- Add nginx config and dockerignore
Resolves: #18
> Dockerfile and nginx configuration

- frontend/src/API.js
- frontend/src/App.js
- frontend/src/views/HomePage/components/ImageTile/ImageTile.js
- frontend/src/views/HomePage/components/ImagesSection/ImagesSection.js
- frontend/src/views/HomePage/components/UploadImage/UploadImage.js
As a user, I want to have a homepage that displays content available in the database.
**Changes**
- Add fetch and map methods
- Add propTypes to ImageTile
- Move APIurl to separated const
Related issue #16
> Fetching images from fake API to homepage

- frontend/src/API.js
- frontend/src/App.js
- frontend/src/contexts/imagesContext.js
- frontend/src/views/HomePage/HomePage.js
- frontend/src/views/HomePage/components/ImageTile/ImageTile.js
- frontend/src/views/HomePage/components/ImagesSection/ImagesSection.js
- frontend/src/views/HomePage/components/UploadImage/UploadImage.js
Fetching API based on a new API model
**Changes:**
- Fetching API methods and components based on a new API model
- Rename API methods
> Integration with new API model

- frontend/src/assets/styles/style.js
- frontend/src/assets/styles/theme.js
- frontend/src/components/Footer/Footer.js
- frontend/src/components/Footer/Footer.styles.js
- frontend/src/views/HomePage/components/UploadImage/UploadImage.js
- frontend/src/views/HomePage/components/UploadImage/UploadImage.styles.js
Modifying styles to improve UI.
**Changes**
- Modified footer
- Modified drag and drop
- Modified theme provider
- Uploaded photo is displayed better on mobile devices
> Modifying styles to improve UI.

- frontend/public/config/config.json
- frontend/src/API.js
- frontend/src/index.js
Allow fetching API inside the cluster
**Changes**
- Add a config file
- API methods use URL from config file
> Fetch kubernetized API

- frontend/src/views/HomePage/components/ImageTile/ImageTile.styles.js
ImageTile is too short (85%). Without title it must be 100%.
> ImageTile height fix

- frontend/src/views/HomePage/components/ImagesSection/ImagesSection.js
- frontend/src/views/HomePage/components/ImagesSection/ImagesSection.styles.js
- frontend/src/views/HomePage/components/UploadImage/UploadImage.js
As a user, I want to know that the application is doing something and I want loading information when images are getting.
> Loading spinner

- resources/backend/apirule.yaml
- resources/backend/deployment.yaml
- resources/backend/service.yaml
- resources/frontend/apirule.yaml
- resources/frontend/deployment.yaml
- resources/frontend/frontend-config.yaml
- resources/frontend/service.yaml
- resources/redis/deployment.yaml
- resources/redis/service.yaml
Yaml deployments, services and config map were updated. API rules files were created.
**Changes**
- adding API rules yaml
- modifying secret name
- renaming deployments and services names
- changing some secret values to env ones
**Related issue** #38
> Updating yaml files

- frontend/nginx.conf
- frontend/src/App.js
As a user, I want to refresh the page and I don't want to see an error page.
> Modify nginx config

- resources/backend/deployment.yaml
> Event type fix

- README.md
We add information about necessary credentials to GCP.
> Update README.md with GCP secrets information

- backend/cmd/main.go
- resources/backend/deployment.yaml
Proper names for env variables.
**Changes**
Modifying env configuration that the names are more informative.
Resolve issue: #72
> Env fields configuration

- resources/functions/font-processing.yaml
- resources/functions/image-processing.yaml
- resources/functions/text-detection.yaml
- resources/subscriptions/font-processing-subscription.yaml
Added font-processing functionality and saves font details to DB.
**Changes**
- Added event which is triggering font-processing function
- Added font-processing YAML file
- Added font-processing subscription file
- Modify console logs for better information
- Separate words and full sentences
> Font-processing function

- resources/functions/handwriting-processing.yaml
- resources/functions/image-processing.yaml
- resources/subscriptions/handwriting-processing-subscription.yaml
Added handwriting-processing functionality and saves handwriting details to DB.
**Changes**
- Added handwriting-processing YAML
- Added handwriting-processing subscription
> Handwriting lambda

- resources/functions/image-processing.yaml
- resources/functions/logo-processing.yaml
- resources/subscriptions/logo-processing-subscription.yaml
Added logo-processing functionality and saves logo details to DB.
**Changes**
- Added handwriting-processing YAML
- Added handwriting-processing subscription
> Logo lambda

- resources/functions/font-processing.yaml
- resources/functions/objects-processing.yaml
- resources/subscriptions/objects-processing-subscription.yaml
Added multiple objects processing functionality and saves details to DB.
**Changes**
- Added multiple objects processing YAML
- Added multiple objects processing subscription
> Adding lambda detecting multiple objects

- resources/functions/labels-handwriting.yaml
- resources/functions/labels-logo.yaml
- resources/functions/labels-text.yaml
- resources/functions/labels.yaml
- resources/functions/objects.yaml
- resources/subscriptions/labels-handwriting-sub.yaml
- resources/subscriptions/labels-logo-sub.yaml
- resources/subscriptions/labels-sub.yaml
- resources/subscriptions/labels-text-sub.yaml
- resources/subscriptions/objects-sub.yaml
We changed the naming convention in functions.
**Changes**
- Rename all functions
> Rename all yaml files

- resources/functions/faces.yaml
- resources/subscriptions/faces-sub.yaml
Added face detection functionality and saving this information to db.
**Changes**
- Added face processing yaml 
- Added face processing subscription
Related issue #67
> Add face processing lambda

- frontend/src/assets/styles/style.js
- frontend/src/views/HomePage/components/ImagesSection/ImagesSection.js
- frontend/src/views/ImageDetailsPage/ImageDetailsPage.js
- frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.js
- frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.styles.js
- frontend/src/views/ImageDetailsPage/components/ImageDetailsArea/ImageDetailsArea.js
Displaying detected text in details section
**Changes**
- Displaying the text that is detected on the image
- The section of details is refreshed when GCP value is null
Related issue: #61
> Display detected text

- resources/functions/faces.yaml
Fix empty json issue
**Changes**
- Added check if face details are empty
- Added recognition for new emotions
> Face detection hotfix

- resources/functions/labels-logo.yaml
Fix logo logo detection function
> fix logo detection

- resources/functions/objects-faces.yaml
- resources/functions/objects.yaml
- resources/subscriptions/objects-faces-sub.yaml
Added face processing functionality triggered by object lambda if 'Person' occurred on the photo.
**Changes**
- faces processing YAML
- faces processing subscription
- objects processing YAML
> Face details processing lambda triggered by object lambda

- README.md
- resources/secrets.yaml
We want to only apply all YAML files with configuration to configure new cluster.
**Changes**
- Add secret YAML file
> Create secret yaml file

- frontend/src/views/ImageDetailsPage/components/FeatureTiles/FaceTile/FaceTile.js
Fix import in FaceTile component
> Fix import in FaceTile component

- resources/functions/labels-text.yaml
- resources/functions/text-category.yaml
- resources/functions/text-entity.yaml
- resources/subscriptions/text-category.yaml
- resources/subscriptions/text-entity-sub.yaml
Added Entity and Category processing functionality
Changes:
- Entity and entity sentiment function
- Category function
- Subscriptions for new functions
- Added event generation in text-font function
> Created Entity and Category processing lambda

- frontend/package-lock.json
- frontend/src/views/ImageDetailsPage/ImageDetailsPage.js
> Redirect to errorpage on bad image id

- frontend/src/contexts/imagesContext.js
- frontend/src/views/HomePage/components/ImagesSection/ImagesSection.js
Images in the feed are sorted by date property.
**Changes**
- Sorting tables of images by date in images context 
**Related issue:** #63
> Sort images by date in feed

- frontend/src/views/HomePage/components/UploadImage/UploadImage.js
useRef is cleaning image value in browser.
**Changes**
Added ref to clear image value in browser.
Resolve: #55
> Fix choosing the same photo to upload

- frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextDocSentimentTile/TextDocSentimentTile.js
- frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextSentenceSentimentTile/TextSentenceSentimentTile.js
- resources/functions/text-entity.yaml
- resources/functions/text-sentiment.yaml
Calculating sentiment in lambda function and putting it in the database.   
**Changes**
- adding function calculating sentiment
- adding the sentiment to the database
- changing displaying on the image details page
Resolve: #124
> Calculating sentiment

- resources/functions/text-sentiment.yaml
Change text-sentiment yaml to use config map with backend's internal url
> Change text-sentiment config

- backend/go.mod
- backend/go.sum
- backend/internal/api/handler.go
- backend/internal/api/handler_test.go
As a user, I want to paste an image directly from the website.
**Changes**
- Added distinction between the image in base64 and URL
- Added tests
- Added validation for extension and max size
Related: #22
> Accepting URL as an image on backend

- frontend/src/views/HomePage/components/UploadImage/UploadImage.js
I forgot to delete some unnecessary things from the code.
> Clean code

- frontend/src/API.js
- frontend/src/views/ImageDetailsPage/components/FeatureTiles/LandmarksMapTile/LandmarksMapTile.js
- frontend/src/views/ImageDetailsPage/components/FeatureTiles/LandmarksMapTile/LandmarksMapTile.styles.js
- frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.js
- resources/frontend/frontend-config.yaml
As a user, I want to see a map of where the detected landmark is.
**Changes**
- Added landmark map component
- Added API_KEY to frontend-config
- Added fetching API_KEY from frontend-config
Resolve: #102
> Displaying landmark map

- frontend/src/views/ImageDetailsPage/ImageDetailsPage.js
- frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.js
- frontend/src/views/ImageDetailsPage/components/ImageDetailsArea/ImageDetailsArea.js
- frontend/src/views/ImageDetailsPage/components/ImageDetailsArea/ImageDetailsArea.styles.js
- resources/functions/nsfw.yaml
- resources/subscriptions/nsfw-sub.yaml
NSFW filter has been added, blurring the image that had NSFW content detected.
**Changes:**
- Added NSFW serverless function 
- Added subscription for NSFW function
- Added frontend functionality that blurs the image on the details page
> NSFW filter 

- frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.js
- resources/functions/text-category.yaml
As a user, I don't want to see /name and Sentence analysis when it's empty.
**Changes**
- Made replace in text-category function
- Repair displaying sentence analysis in ImageDetailsArea
Resolve: #149, #146
> Repair / and sentece bug
